required = ["github.com/docker/distribution"]

[[constraint]]
  branch = "master"
  name = "github.com/cuigh/auxo"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"
  source = "https://github.com/moby/moby.git"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.3.0"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.2"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"